import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import type { NextFontWithVariable } from "next/dist/compiled/@next/font";
import "material-symbols/outlined.css";
import "./globals.css";
import { cn } from "@/lib/utils";

const inter: NextFontWithVariable = Inter({ subsets: ['latin'], variable: '--font-sans' });

const geistSans: NextFontWithVariable = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono: NextFontWithVariable = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, "font-sans", inter.variable)}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
